[package]
name = "sc-lfs"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Large File Storage for Substrate"
edition = "2018"

[dependencies.sc-lfs-rpc]
path = "./rpc"

[dependencies.sp-lfs-core]
path = "../primitives/core"

[dependencies]
libp2p = "0.13.1"
codec = { package = "parity-scale-codec", version = "1.1.2" }
