language: rust
cache:
  cargo: true
  timeout: 1000

rust:
  - nightly

script:
  - rustup target install wasm32-unknown-unknown
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

notifications:
  email:
    on_success: never
    on_failure: never
