language: rust
cache: cargo

rust:
  - nightly

script:
  - command -v wasm-gc || cargo install --git https://github.com/alexcrichton/wasm-gc --force
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

notifications:
  email:
    on_success: never
    on_failure: never
