language: rust
cache: cargo

rust:
  - nightly

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

notifications:
  email:
    on_success: never
    on_failure: never
