[workspace]
members = [
    # primitives
    "primitives/core",
    "primitives/cache",

    # client
    "client/simple-cache",
    "client",

    # frame pallet
    "pallet",

    # demo implementation
    "demo",
]

default-members = ["demo"]
