[package]
name = "pallet-lfs"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '1.0.0' }
support = { default_features = false, git = 'https://github.com/paritytech/substrate.git', package = 'frame-support', rev  = "da816e2" }
system = { default_features = false, git = 'https://github.com/paritytech/substrate.git', package = 'frame-system', rev  = "da816e2" }
app_crypto = { default_features = false, git = 'https://github.com/paritytech/substrate.git', package = "sp-application-crypto", rev  = "da816e2" }
rstd = { default_features = false, git = 'https://github.com/paritytech/substrate.git', package = 'sp-std', rev  = "da816e2" }
sp-io = { default_features = false, git = "https://github.com/paritytech/substrate", rev  = "da816e2" }
sp-runtime = { default_features = false, git = 'https://github.com/paritytech/substrate.git', package = 'sp-runtime', rev  = "da816e2"}

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'support/std',
    'system/std',
    'app_crypto/std',
    'rstd/std',
    'sp-io/std',
    'sp-runtime/std',
]
