[package]
name = "lfs-demo"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"
default-run = "lfs-demo"
publish = false

[[bin]]
name = "lfs-demo"
path = "src/main.rs"

[dependencies]
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sp-io = { git = "https://github.com/paritytech/substrate", rev = "fe07382" }
sc-cli = { git = "https://github.com/paritytech/substrate", rev = "fe07382" }
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
sc-executor = { git = "https://github.com/paritytech/substrate", rev = "fe07382" }
sc-service = { git = "https://github.com/paritytech/substrate", rev = "fe07382" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
txpool = { package = "sc-tracing-pool", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
network = { package = "sc-network", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
aura = { package = "sc-consensus-aura", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
aura-primitives = { package = "sp-consensus-aura", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
consensus-common = { package = "sp-consensus", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
grandpa-primitives = { package = "sp-finality-granpda", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
sc-client = {  git = "https://github.com/paritytech/substrate", rev = "fe07382" }
runtime = { package = "lfs-demo-runtime", path = "./runtime" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "fe07382" }
basic-authorship = { package = "sc-basic-authority", git = "https://github.com/paritytech/substrate", rev = "fe07382" }

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { package = "substrate-build-script-utils", git = "https://github.com/paritytech/substrate", rev = "fe07382" }
