[package]
name = "lfs-demo"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"
default-run = "lfs-demo"
publish = false

[[bin]]
name = "lfs-demo"
path = "src/main.rs"

[dependencies.lfs-demo-runtime]
path = "./runtime"

[dependencies.sc-lfs]
path = "../client"
features = ["std", "jsonrpc"]

[dependencies]
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sp-io = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-cli = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-executor = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-service = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-network = { version = "0.8", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-consensus-aura = { version = "0.8", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sp-consensus-aura = { version = "0.8", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sp-consensus = { version = "0.8", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
grandpa = { version = "2.0.0", package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
grandpa-primitives = { version = "2.0.0", package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-client = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
sc-basic-authority = { git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }

jsonrpc-core =  "14.0.5"

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { version = "2.0.0", package = "substrate-build-script-utils", git = "https://github.com/paritytech/substrate", rev = "05b596f1ac3e3187717a87b1616706fe7511abcc" }
